name: CD

on:
    # Trigger the workflow manually with the `workflow_dispatch` event
    workflow_dispatch: 
      inputs:
        major:
          description: Year # The year of the release, e.g., 24 for 2024
          type: number 
          required: true
          default: '24'
        minor:
          description: Release # The minor version of the release, e.g., 4 for the fourth release of the year
          type: number 
          required: true
          default: '5'
        build:
          description: Beta # The build number, typically used for beta versions
          type: number 
          required: true
          default: '0'
        revision:
          description: Alpha # The revision number, typically used for alpha versions
          type: number 
          required: true
          default: '0'
        SSLCert:
          description: "Add Certificate" # Option to add an SSL certificate
          type: choice
          required: true
          default: 'No'
          options:
          - 'Yes' # Add SSL certificate
          - 'No'  # Do not add SSL certificate
jobs:            
    Builder:
        name: CD
        runs-on: windows-latest
        steps:
            -   name: Restore static site content
                uses: actions/cache@v4
                with:
                    path: ./**
                    key: cache-site-windows-${{ github.run_number }}
                    enableCrossOsArchive:
                        true       
            
            -   uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
                with: 
                    filepath: './Ginger/inno.iss'  
                  
            - name: print files 
              if: ${{ github.event.inputs.SSLCert != 'No' }}
              run: |    
                  ls
                    
            -   name: Upload Windows Installer
                uses: actions/upload-artifact@v3
                with:
                  name: WindowsInstaller
                  path: D:/a/Installers
            
        
