name: dockerdemo

on:
  workflow_dispatch: 
    inputs:
      Version:
        type: string 
        required: true
  workflow_call:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Deploy
    permissions:
      contents: read
      packages: write
    
    env:
      BUILD_CONFIGURATION: Release
      
    steps:    
# ------------------------------------------------------------------------------------------------------
# Createin version Tag & Number variables 
# ------------------------------------------------------------------------------------------------------
      -   name: Create Version Environment Variable
          id: set_version
          if: ${{github.workflow == 'CD'}} 
          run: |
              if [[ ${{github.event.inputs.revision}} != 0 ]]; then 
                  echo "Alpha Version"
                  echo "gingertag=20${{ github.event.inputs.major}}.${{ github.event.inputs.minor}}-Alpha.${{github.event.inputs.build}}.${{ github.event.inputs.revision}}" >> $GITHUB_ENV
              elif [[ ${{github.event.inputs.build}} != 0 && ${{github.event.inputs.revision}} == 0 ]]; then
                  echo "Beta Version"
                  echo "gingertag=20${{ github.event.inputs.major}}.${{ github.event.inputs.minor}}-Beta.${{ github.event.inputs.build}}" >> $GITHUB_ENV
              elif [[ ${{github.event.inputs.build}} == 0  &&  ${{github.event.inputs.revision}} == 0 ]]; then
                  echo "Official Version"
                  echo "gingertag=20${{ github.event.inputs.major}}.${{ github.event.inputs.minor}}-Official" >> $GITHUB_ENV
              fi
              echo "ginger gingertag ${{env.gingertag}}"
          
      - name: Restore static site content
        uses: actions/cache@v3.2.6
        with:
          path: ./**
          key: cache-site-linux-${{ github.run_number }}
          enableCrossOsArchive:
            true  

# ------------------------------------------------------------------------------------------------------
# Log in to the Container registry - GHCR
# ------------------------------------------------------------------------------------------------------
      - name: Log in to the Container registry - GHCR
        run: | 
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} 
# ------------------------------------------------------------------------------------------------------
# Create GingerRuntime docker image
# ------------------------------------------------------------------------------------------------------
      - name: Building GingerRuntime docker image
        run: |
          cd Ginger/GingerRuntime
          ls -altr
          echo "==========================================================="
          ls -altr ./bin
          echo "==========================================================="
          ls -altr ./bin/Release
          echo "==========================================================="
          ls -altr ./bin/Release/net8.0
          echo "==========================================================="
          ls -altr ./bin/Release/net8.0/linux-x64
          echo "==========================================================="

          docker build -t gingerruntime .
        
      - name: Change image tag to be pushed for GHCR
        run: |
          docker tag gingerruntime ghcr.io/${{ github.actor }}/gingerruntime:"${{ env.gingertag}}"
          
      # - name: Pushing GingerRuntime Image
      #   run: | 
      #     docker push ghcr.io/${{ github.actor }}/gingerruntime:"${{ env.gingertag}}"

      - name: Change image tag(latest) to be pushed for GHCR
        run: |
          docker tag gingerruntime ghcr.io/${{ github.actor }}/gingerruntime:latest
          
      # - name: Pushing GingerRuntime Image
      #   run: | 
      #     docker push ghcr.io/${{ github.actor }}/gingerruntime:latest
