name: MacOS Unit-Test

on:
  workflow_call:
      
  # pull_request:
  #   branches: 
  #     - master
  #     - Features/Linux-Migration
  #     - Releases/*
  #     - Releases/*/*

  # push:
  #   branches:
  #     - '**'

jobs:
  build:
    name: MacOS Test
    runs-on: macOS-latest
    
    env:
      BUILD_CONFIGURATION: Release
    
    steps:   
    
# ------------------------------------------------------------------------------------------------------
# Restore static site content
# ------------------------------------------------------------------------------------------------------ 
      - name: Restore static site content
        uses: actions/cache@v3.2.6
        with:
          path: ./**
          key: cache-site-macos-${{ github.run_number }}
          enableCrossOsArchive:
            truet

# ------------------------------------------------------------------------------------------------------
# Install .Net core SDK 8.0.100
# ------------------------------------------------------------------------------------------------------
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.100'
    
# ------------------------------------------------------------------------------------------------------
# start Testing 
# ------------------------------------------------------------------------------------------------------
      - name: 'Testing GingerUtilsTest'
        run: dotnet test  Ginger/GingerUtilsTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
      
      - name: 'Testing GingerCoreCommonTest'
        if: success() || failure()        # run this step even if previous step failed
        run: dotnet test  Ginger/GingerCoreCommonTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal

      - name: 'Testing GingerCoreNETUnitTest'
        if: success() || failure()        # run this step even if previous step failed
        run: dotnet test  Ginger/GingerCoreNETUnitTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal

      - name: 'Testing GingerPluginCoreTest'
        if: success() || failure()        # run this step even if previous step failed
        run: dotnet test  Ginger/GingerPluginCoreTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal

      - name: 'Testing GingerConsoleTest'
        if: success() || failure()        # run this step even if previous step failed
        run: dotnet test  Ginger/GingerConsoleTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal

      - name: 'Testing GingerAutoPilotTest'
        if: success() || failure()        # run this step even if previous step failed
        run: dotnet test  Ginger/GingerAutoPilotTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
             
# ------------------------------------------------------------------------------------------------------
# Publish Test Results
# ------------------------------------------------------------------------------------------------------
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: Ginger MacOS UnitTests    # Name of the check run which will be created
          path: "**/*.trx"                # Path to test results
          reporter: dotnet-trx            # Format of test results        
